# Generated by Django 3.0.8 on 2020-08-15 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phno',
            field=models.IntegerField(),
        ),
    ]
